apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "tekton-custom-task.labels" . | nindent 4 }}
  name: edp-{{ .Values.name }}-{{ .Release.Namespace }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edp-{{ .Values.name }}-{{ .Release.Namespace }}-role
subjects:
- kind: ServiceAccount
  name: edp-{{ .Values.name }}
  namespace: {{ .Release.Namespace }}
