#CRD for integration tests
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customruns.tekton.dev
  labels:
    pipeline.tekton.dev/release: v0.62.0
    version: v0.62.0
spec:
  group: tekton.dev
  names:
    plural: customruns
    singular: customrun
    kind: CustomRun
    listKind: CustomRunList
    categories:
      - tekton
      - tekton-pipelines
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Succeeded
          type: string
          jsonPath: .status.conditions[?(@.type=="Succeeded")].status
        - name: Reason
          type: string
          jsonPath: .status.conditions[?(@.type=="Succeeded")].reason
        - name: StartTime
          type: date
          jsonPath: .status.startTime
        - name: CompletionTime
          type: date
          jsonPath: .status.completionTime
  conversion:
    strategy: None
